# This is a basic workflow to help you get started with Actions

name: CI

on:
 # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Test:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        os:             [ubuntu-latest] 
        # macos-latest really takes long and windows-latest fails with memory error in compilation (with nim stable, not with nim devel)
        nim-channel:    [stable, devel]

    name: ${{ matrix.os }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Test
      shell: bash
      run: |
        nim --version
        nim --run --mm:arc c test.nim 
        nim --run --d:release c test.nim 
        nim --run js test.nim
        nim --run --d:release js test.nim
